<a href="https://colab.research.google.com/github/AsifQuasmi/Data-Science/blob/master/04_Numpy_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [17]:
import numpy as np

#### Create an array of 10 zeros 

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [20]:
arr = np.array(5)
arr

array(5)

#### Create an array of the integers from 10 to 50

array(5)

IndexError: ignored

In [24]:
arr = (np.arange(0,11))

#### Create an array of all the even integers from 10 to 50

In [25]:
arr[:] = 5

#### Create a 3x3 matrix with values ranging from 0 to 8

In [26]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create a 3x3 identity matrix

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [30]:
np.random.rand(10)

array([0.15406195, 0.38466197, 0.62013677, 0.76676777, 0.89708737,
       0.56021657, 0.66101692, 0.54344816, 0.48144788, 0.07156614])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [34]:
a = (np.random.randint(1,1000,25))
a.sort()

#### Create the following matrix:

In [35]:
a

array([ 60,  98, 148, 214, 307, 326, 387, 413, 456, 470, 562, 581, 587,
       593, 699, 740, 742, 846, 861, 957, 970, 975, 980, 982, 985])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [42]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [37]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [38]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

### Now do the following

#### Get the sum of all the values in mat

In [39]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [43]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [44]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

# Great Job!