<a href="https://colab.research.google.com/github/AsifQuasmi/Data-Science/blob/master/NumpyBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
seq = [1,2,3]

In [2]:
import numpy as np
arr = np.array(seq)

In [3]:
arr

array([1, 2, 3])

In [4]:
my_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.random.rand(5)

array([0.17946703, 0.49031961, 0.79566699, 0.78827069, 0.29984624])

In [14]:
np.random.rand(5,5)

array([[0.45739445, 0.37857974, 0.6754158 , 0.02823409, 0.69837655],
       [0.89190606, 0.61689629, 0.65748814, 0.08448685, 0.22334331],
       [0.1360844 , 0.37308786, 0.2307968 , 0.83305328, 0.70307081],
       [0.64771459, 0.39719874, 0.23667571, 0.31600275, 0.60849752],
       [0.77683918, 0.72358698, 0.9652852 , 0.26299529, 0.90034754]])

In [15]:
np.random.randint(1,100)

65

In [16]:
np.random.randint(1,1000,13)

array([895, 826, 185, 281, 831, 123, 906, 507, 139, 448, 584, 836, 531])

In [17]:
np.sort(np.random.randint(1,100,10))

array([ 6, 41, 43, 43, 47, 49, 63, 66, 76, 81])

In [18]:
arr = np.arange(50)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [21]:
arr.max()


49

In [24]:
np.random.randint(1,100,10).max()

99

In [25]:
arr.min()

0

In [26]:
arr.min()

0

In [27]:
arr.argmax()

49

In [34]:
seq = np.random.randint(0,100,20)

In [29]:
seq

array([76, 25,  7, 79,  9, 26, 24, 22, 60, 27, 24, 36, 72, 24,  2, 76, 90,
       99, 80,  0])

In [35]:
print(seq)
seq.argmax()


[22 97 53 49 79  7 81 84 24  5 90 40 49 79 99 53 88 78 97 67]


14

In [36]:
print(seq)
seq.argmin()



[22 97 53 49 79  7 81 84 24  5 90 40 49 79 99 53 88 78 97 67]


9

In [37]:
arr.shape

(50,)

In [38]:
arr.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [39]:
arr.shape

(50,)

In [40]:
arr = np.arange(10)

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [43]:
arr[1:7]

array([1, 2, 3, 4, 5, 6])

In [44]:
arr[0:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr[5:]

array([5, 6, 7, 8, 9])

In [46]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[0:5] = 10

In [48]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [49]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [55]:
slice_of_arr = arr[:5]

In [56]:
slice_of_arr[:] = 10

In [57]:
slice_of_arr

array([10, 10, 10, 10, 10])

In [58]:
slice_of_arr[:] = 100

In [59]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [60]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [61]:
slice_of_arr[:] = 11

In [62]:
slice_of_arr

array([11, 11, 11, 11, 11])

In [63]:
arr

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9])

In [68]:
slice_of_arr  = arr.copy()

In [69]:
slice_of_arr

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9])

In [70]:
slice_of_arr[:] = 10002

In [71]:
arr

array([11, 11, 11, 11, 11,  5,  6,  7,  8,  9])

In [72]:
slice_of_arr

array([10002, 10002, 10002, 10002, 10002, 10002, 10002, 10002, 10002,
       10002])